[project]
name = "2025-inkindcontributions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "coloredlogs>=15.0.1",
    "fmpy[complete,gui]>=0.3.32",
    "grpcio>=1.84.0",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "protobuf==3.20.3",
    "pyside6>=6.11.2",
    "pyzmq>=27.2.0",
    "setuptools<81",
    "toml>=0.10.2",
    "unifmu[python-backend]>=0.0.3",
]
