FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY fmu_runner_opc.py /app/

ENV FMU_PATH=/app/model.fmu
ENV RESULTS_DIR=/results
ENV START_TIME=0.0
ENV STOP_TIME=10.0
ENV STEP_SIZE=1.0
ENV STEP_DELAY=0.5
ENV OPCUA_ENDPOINT=opc.tcp://opcua-server:4840

CMD ["python", "fmu_runner_opc.py"]
