networks:
  simnet:
    name: simnet     # Nombre fijo y visible para todos los servicios
    driver: bridge

services:
  opcua-server:
    build: ./opcua_server
    container_name: opcua-server
    networks: [simnet]
    ports:
      - "4841:4840"

  streamlit-ui:
    build: ./streamlit_ui
    container_name: streamlit-ui
    networks: [simnet]
    ports: ["8501:8501"]
    environment:
      - OPCUA_ENDPOINT=opc.tcp://opcua-server:4840
      - DOCKER_NETWORK=simnet
      - FMU_IMAGE=fmu-client:latest
      - FMU_CONTAINER_NAME_BASE=fmu-run
      - HOST_FMU_PATH=${HOST_FMU_PATH}
      - HOST_RESULTS_PATH=${HOST_RESULTS_PATH}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./results:/results



  fmu-client:
    build: ./fmu_client
    image: fmu-client:latest
    container_name: fmu-client
    networks: [simnet]
    environment:
      - OPCUA_ENDPOINT=opc.tcp://opcua-server:4840
      - FMU_PATH=/app/model.fmu
      - RESULTS_DIR=/results
      - OPC_WAIT=10
    volumes:
      - ./model/ORIGINAL_generated_auto.fmu:/app/model.fmu:ro
      - ./results:/results

