FROM python:3.11-slim

RUN pip install --no-cache-dir streamlit opcua cryptography docker

WORKDIR /app
COPY streamlit_app.py /app/

EXPOSE 8501
ENV OPCUA_ENDPOINT=opc.tcp://opcua-server:4840
CMD ["streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]



