"""Generic FMI 2 UniFMU adapter generated by fmugen.

This file is identical for every model. It translates the FMI 2 calls forwarded by
UniFMU's backend (backend.py) into the fmugen runtime engine (fmugen_runtime.py),
which runs the user's unmodified code as described by interface.json.
"""
from pathlib import Path

try:
    from fmugen_runtime import Engine, Status
except ImportError:  # imported from the fmugen package (build probe, tests)
    from fmugen.templates.fmugen_runtime import Engine, Status

RESOURCES_DIR = Path(__file__).resolve().parent


class Model:
    def __init__(self, _log_callback, resources_dir=None) -> None:
        self._log_callback = _log_callback # Removing this line will break logging
        self.engine = Engine(resources_dir or RESOURCES_DIR, self.log, info_category="logAll")

    # ================= FMI2 =================

    def fmi2DoStep(
        self, current_time, step_size, no_set_fmu_state_prior_to_current_point
    ):
        status, _ = self.engine.do_step(current_time, step_size)
        return status

    def fmi2SetDebugLogging(self, categories, logging_on):
        self.engine.logging_on = bool(logging_on)
        return Fmi2Status.ok

    def fmi2EnterInitializationMode(self):
        return self.engine.enter_initialization_mode()

    def fmi2ExitInitializationMode(self):
        return self.engine.exit_initialization_mode()

    def fmi2SetupExperiment(self, start_time, stop_time, tolerance):
        return self.engine.setup_experiment(start_time, stop_time, tolerance)

    def fmi2Terminate(self):
        return self.engine.terminate()

    def fmi2Reset(self):
        return self.engine.reset()

    def fmi2SerializeFmuState(self):
        return self.engine.serialize()

    def fmi2DeserializeFmuState(self, bytes):
        return self.engine.deserialize(bytes)

    def fmi2GetReal(self, references):
        return self.engine.get_values(references)

    def fmi2GetInteger(self, references):
        return self.engine.get_values(references)

    def fmi2GetBoolean(self, references):
        return self.engine.get_values(references)

    def fmi2GetString(self, references):
        return self.engine.get_values(references)

    def fmi2SetReal(self, references, values):
        return self.engine.set_values(references, values)

    def fmi2SetInteger(self, references, values):
        return self.engine.set_values(references, values)

    def fmi2SetBoolean(self, references, values):
        return self.engine.set_values(references, values)

    def fmi2SetString(self, references, values):
        return self.engine.set_values(references, values)

    # ================= Logging =================

    def log(self, message, status, category = "logAll"):
        # Removing the line below will break logging.
        self._log_callback(status, category, message)


class Fmi2Status(Status):
    """
    Represents the status of an FMI2 FMU or the results of function calls.

    Values:
        * ok: all well
        * warning: an issue has arisen, but the computation can continue.
        * discard: an operation has resulted in invalid output, which must be discarded
        * error: an error has ocurred for this specific FMU instance.
        * fatal: an fatal error has ocurred which has corrupted ALL FMU instances.
        * pending: indicates that the FMu is doing work asynchronously, which can be retrived later.

    Notes:
        FMI section 2.1.3

    """

    pending = 5
