"""Generic UniFMU adapter generated by fmugen.

This file is identical for every model. The model-specific parts live next to it:
- interface.json: variables, value references and start values
- <model_module>.py: the user model, which exposes step(**inputs) -> dict
"""
import importlib
import json
import pickle
from pathlib import Path

RESOURCES_DIR = Path(__file__).resolve().parent


class Model:
    def __init__(self, _log_callback) -> None:
        self._log_callback = _log_callback # Removing this line will break logging

        self.interface = json.loads((RESOURCES_DIR / "interface.json").read_text())
        self.variables = self.interface["variables"]
        self.user_model = importlib.import_module(self.interface["model_module"])

        self.reference_to_attribute = {
            v["valueReference"]: v["name"] for v in self.variables
        }
        self.input_names = [v["name"] for v in self.variables if v["causality"] != "output"]
        self.output_names = [v["name"] for v in self.variables if v["causality"] == "output"]
        self._defaults = {
            v["name"]: v.get("start", _default_value(v["type"])) for v in self.variables
        }

        self.fmi2Reset()

    # ================= FMI2 =================

    def fmi2DoStep(
        self, current_time, step_size, no_set_fmu_state_prior_to_current_point
    ):
        return self._update_outputs()

    def fmi2SetDebugLogging(self, categories, logging_on):
        return Fmi2Status.ok

    def fmi2EnterInitializationMode(self):
        return Fmi2Status.ok

    def fmi2ExitInitializationMode(self):
        return self._update_outputs()

    def fmi2SetupExperiment(self, start_time, stop_time, tolerance):
        return Fmi2Status.ok

    def fmi2Terminate(self):
        return Fmi2Status.ok

    def fmi2Reset(self):
        for name, value in self._defaults.items():
            setattr(self, name, value)
        return self._update_outputs()

    def fmi2SerializeFmuState(self):
        state = {name: getattr(self, name) for name in self._defaults}
        return Fmi2Status.ok, pickle.dumps(state)

    def fmi2DeserializeFmuState(self, bytes):
        for name, value in pickle.loads(bytes).items():
            setattr(self, name, value)
        return Fmi2Status.ok

    def fmi2GetReal(self, references):
        return self._get_value(references)

    def fmi2GetInteger(self, references):
        return self._get_value(references)

    def fmi2GetBoolean(self, references):
        return self._get_value(references)

    def fmi2GetString(self, references):
        return self._get_value(references)

    def fmi2SetReal(self, references, values):
        return self._set_value(references, values)

    def fmi2SetInteger(self, references, values):
        return self._set_value(references, values)

    def fmi2SetBoolean(self, references, values):
        return self._set_value(references, values)

    def fmi2SetString(self, references, values):
        return self._set_value(references, values)

    # ================= Logging =================

    def log(self, message, status, category = "logAll"):
        # Removing the line below will break logging.
        self._log_callback(status, category, message)

    # ================= Helpers =================

    def _set_value(self, references, values):

        for r, v in zip(references, values):
            setattr(self, self.reference_to_attribute[r], v)

        return Fmi2Status.ok

    def _get_value(self, references):

        values = []

        for r in references:
            values.append(getattr(self, self.reference_to_attribute[r]))

        return Fmi2Status.ok, values

    def _update_outputs(self):
        try:
            results = self.user_model.step(
                **{name: getattr(self, name) for name in self.input_names}
            )
            for name in self.output_names:
                setattr(self, name, results[name])
        except Exception as e:
            self.log(f"model step failed: {e!r}", Fmi2Status.error, "logStatusError")
            return Fmi2Status.error
        return Fmi2Status.ok


def _default_value(fmi_type):
    return {"Real": 0.0, "Integer": 0, "Boolean": False, "String": ""}[fmi_type]


class Fmi2Status:
    """
    Represents the status of an FMI2 FMU or the results of function calls.

    Values:
        * ok: all well
        * warning: an issue has arisen, but the computation can continue.
        * discard: an operation has resulted in invalid output, which must be discarded
        * error: an error has ocurred for this specific FMU instance.
        * fatal: an fatal error has ocurred which has corrupted ALL FMU instances.
        * pending: indicates that the FMu is doing work asynchronously, which can be retrived later.

    Notes:
        FMI section 2.1.3

    """

    ok = 0
    warning = 1
    discard = 2
    error = 3
    fatal = 4
    pending = 5
