"""Generic UniFMU adapter generated by fmugen.

This file is identical for every model. The model-specific parts live next to it:
- interface.json: variables, value references, start values and how each variable
  is bound to the user's Python code (constructor argument, call argument,
  attribute, return value, ...)
- fmugen_model/: the user's code, copied unchanged
- site/: vendored requirements (only with `fmugen build --vendor`)

The user's code is never modified. It can be a function called once per step, or a
class that is constructed on initialization and whose method is called once per step.
"""
import ast
import contextlib
import importlib
import json
import logging
import math
import pickle
import sys
import traceback
from collections.abc import Mapping
from pathlib import Path

RESOURCES_DIR = Path(__file__).resolve().parent
DEFAULT_VALUES = {"Real": 0.0, "Integer": 0, "Boolean": False, "String": "", "Enumeration": 1}


class Model:
    def __init__(self, _log_callback, resources_dir=None) -> None:
        self._log_callback = _log_callback # Removing this line will break logging

        self.resources_dir = Path(resources_dir) if resources_dir else RESOURCES_DIR
        self.interface = json.loads((self.resources_dir / "interface.json").read_text())
        self.variables = self.interface["variables"]
        self.by_reference = {v["valueReference"]: v for v in self.variables}
        self.experiment = self.interface.get("experiment", {})

        self.logging_on = True
        self.entry = load_entry(self.interface, self.resources_dir)
        entry = self.interface["entry"]
        self.is_class = entry["kind"] == "class"
        self.enums = {
            name: resolve_reference(td["enum"])
            for name, td in self.interface.get("type_definitions", {}).items() if td.get("enum")
        }
        self.constants = {k: resolve_constant(v) for k, v in self.interface.get("constants", {}).items()}
        self.call_constants = {k: resolve_constant(v) for k, v in self.interface.get("call_constants", {}).items()}

        self.fmi2Reset()

    # ================= FMI2 =================

    def fmi2DoStep(
        self, current_time, step_size, no_set_fmu_state_prior_to_current_point
    ):
        if self.mode != "step":
            return self._error(f"fmi2DoStep called in mode {self.mode!r}; exit initialization mode first")
        fixed = self.experiment.get("step_size") if self.experiment.get("fixed_step") else None
        if fixed is not None and not math.isclose(step_size, fixed, rel_tol=1e-9, abs_tol=1e-12):
            return self._error(f"this FMU only supports a communication step size of {fixed}, got {step_size}")

        def advance():
            result = self._call(current_time, step_size)
            self._read_results(result, have_result=True, update_states=True, missing_ok=False)

        status = self._run("doStep", advance)
        if status == Fmi2Status.ok:
            self.time = current_time + step_size
        return status

    def fmi2SetDebugLogging(self, categories, logging_on):
        self.logging_on = bool(logging_on)
        return Fmi2Status.ok

    def fmi2EnterInitializationMode(self):
        self.mode = "initialization"
        return Fmi2Status.ok

    def fmi2ExitInitializationMode(self):
        def initialize():
            if self.is_class:
                kwargs = dict(self.constants)
                kwargs.update(self._bound("init"))
                self.obj = self.entry(**kwargs)
                self._apply_attributes()
            if self.interface["entry"].get("init_call"):
                result = self._call(self.time, self.experiment.get("step_size", 0.0))
                self._read_results(result, have_result=True, update_states=False, missing_ok=True)
            else:
                self._read_results(None, have_result=False, update_states=False, missing_ok=True)

        status = self._run("initialization", initialize)
        if status == Fmi2Status.ok:
            self.mode = "step"
        return status

    def fmi2SetupExperiment(self, start_time, stop_time, tolerance):
        self.time = start_time
        self.start_time, self.stop_time, self.tolerance = start_time, stop_time, tolerance
        return Fmi2Status.ok

    def fmi2Terminate(self):
        method = self.interface["entry"].get("terminate")
        status = Fmi2Status.ok
        if method and self.obj is not None:
            status = self._run("terminate", lambda: getattr(self.obj, method)())
        self.mode = "terminated"
        return status

    def fmi2Reset(self):
        self.values = {
            v["name"]: v.get("start", DEFAULT_VALUES[v["type"]]) for v in self.variables
        }
        self.obj = None
        self.mode = "instantiated"
        self.time = self.experiment.get("start_time", 0.0)
        self.start_time, self.stop_time, self.tolerance = self.time, None, None
        return Fmi2Status.ok

    def fmi2SerializeFmuState(self):
        state = {"values": self.values, "obj": self.obj, "time": self.time, "mode": self.mode}
        try:
            return Fmi2Status.ok, pickle.dumps(state)
        except Exception as e:
            self.log(f"cannot serialize FMU state: {e!r}", Fmi2Status.error, "logStatusError")
            return Fmi2Status.error, b""

    def fmi2DeserializeFmuState(self, bytes):
        try:
            state = pickle.loads(bytes)
        except Exception as e:
            return self._error(f"cannot deserialize FMU state: {e!r}")
        self.values = dict(state["values"])
        self.obj, self.time, self.mode = state["obj"], state["time"], state["mode"]
        return Fmi2Status.ok

    def fmi2GetReal(self, references):
        return self._get_value(references)

    def fmi2GetInteger(self, references):
        return self._get_value(references)

    def fmi2GetBoolean(self, references):
        return self._get_value(references)

    def fmi2GetString(self, references):
        return self._get_value(references)

    def fmi2SetReal(self, references, values):
        return self._set_value(references, values)

    def fmi2SetInteger(self, references, values):
        return self._set_value(references, values)

    def fmi2SetBoolean(self, references, values):
        return self._set_value(references, values)

    def fmi2SetString(self, references, values):
        return self._set_value(references, values)

    # ================= Logging =================

    def log(self, message, status, category = "logAll"):
        # Removing the line below will break logging.
        self._log_callback(status, category, message)

    @contextlib.contextmanager
    def _forward_logs(self):
        """Forward `logging` records emitted by the user's code to the importer.

        The handler is only installed while user code runs, because UniFMU can only
        carry a log message while it is processing a command.
        """
        handler = _ForwardingHandler(self)
        root = logging.getLogger()
        root.addHandler(handler)
        try:
            yield
        finally:
            root.removeHandler(handler)

    # ================= Helpers =================

    def _error(self, message):
        self.log(message, Fmi2Status.error, "logStatusError")
        return Fmi2Status.error

    def _run(self, what, fn):
        try:
            with self._forward_logs():
                fn()
        except Exception as e:
            return self._error(f"{what} failed: {e!r}\n{traceback.format_exc()}")
        return Fmi2Status.ok

    def _set_value(self, references, values):

        for r, v in zip(references, values):
            var = self.by_reference.get(r)
            if var is None:
                return self._error(f"unknown value reference {r}")
            name, causality = var["name"], var["causality"]
            settable = causality in ("input", "parameter") or (
                causality == "local" and var.get("initial") == "exact" and self.mode != "step"
            )
            if not settable:
                return self._error(f"{name} ({causality}) cannot be set")
            if self.mode == "step" and causality == "parameter" and var["variability"] != "tunable":
                return self._error(f"{name} is a fixed parameter and cannot be changed after initialization")
            self.values[name] = coerce(var["type"], v)

            if self.mode == "step" and causality == "parameter" and self.obj is not None and var.get("attr"):
                status = self._run(
                    f"setting {name}",
                    lambda: setattr(self.obj, var["attr"], self._to_python(var, self.values[name])),
                )
                if status != Fmi2Status.ok:
                    return status
                self._run("updating calculated parameters", self._refresh_calculated_parameters)

        return Fmi2Status.ok

    def _get_value(self, references):

        values = []

        for r in references:
            var = self.by_reference.get(r)
            if var is None:
                self.log(f"unknown value reference {r}", Fmi2Status.error, "logStatusError")
                return Fmi2Status.error, []
            values.append(self.values[var["name"]])

        return Fmi2Status.ok, values

    def _to_python(self, var, value):
        enum = self.enums.get(var.get("declared_type"))
        if enum is not None:
            return list(enum)[value - 1]
        return value

    def _from_python(self, var, value):
        if var["type"] == "Enumeration":
            enum = self.enums.get(var.get("declared_type"))
            if enum is not None and isinstance(value, enum):
                return list(enum).index(value) + 1
        if value is None:
            raise TypeError(f"{var['name']} is None")
        return coerce(var["type"], value)

    def _bound(self, kind):
        """{python name: value} of every variable bound to a constructor/call argument."""
        return {
            v["to"]["name"]: self._to_python(v, self.values[v["name"]])
            for v in self.variables if v.get("to", {}).get("kind") == kind
        }

    def _call(self, time, step_size):
        kwargs = dict(self.call_constants if self.is_class else self.constants)
        kwargs.update(self._bound("arg"))
        sources = {"time": time, "step_size": step_size, "end_time": time + step_size}
        for arg, source in self.interface.get("time_args", {}).items():
            kwargs[arg] = sources[source]
        self._apply_attributes()
        if self.is_class:
            return getattr(self.obj, self.interface["entry"]["call"])(**kwargs)
        return self.entry(**kwargs)

    def _apply_attributes(self):
        """Write variables bound to attributes (to = "attr:...") onto the model object."""
        for v in self.variables:
            if v.get("to", {}).get("kind") == "attr":
                set_path(self.obj, v["to"]["name"], self._to_python(v, self.values[v["name"]]))

    def _source_value(self, source, result, have_result):
        """Return (found, value) for a {"kind": "return"|"attr", "name": ...} source."""
        if source["kind"] == "return":
            if not have_result:
                return False, None
            return True, pick(result, source.get("name"))
        return True, get_path(self.obj, source["name"])

    def _read_results(self, result, have_result, update_states, missing_ok):
        for v in self.variables:
            if "from" not in v:
                continue
            try:
                found, value = self._source_value(v["from"], result, have_result)
            except (AttributeError, KeyError, IndexError) as e:
                if missing_ok:
                    continue
                raise LookupError(f"{v['name']}: cannot read {describe(v['from'])} ({e!r})") from e
            if found:
                self.values[v["name"]] = self._from_python(v, value)
        if update_states:
            for v in self.variables:
                if "next" in v:
                    try:
                        _, value = self._source_value(v["next"], result, True)
                    except (AttributeError, KeyError, IndexError) as e:
                        raise LookupError(f"state {v['name']}: cannot read {describe(v['next'])} ({e!r})") from e
                    self.values[v["name"]] = self._from_python(v, value)

    def _refresh_calculated_parameters(self):
        for v in self.variables:
            if v["causality"] == "calculatedParameter" and v["from"]["kind"] == "attr":
                self.values[v["name"]] = self._from_python(v, get_path(self.obj, v["from"]["name"]))


class _ForwardingHandler(logging.Handler):
    def __init__(self, model):
        super().__init__(level=logging.DEBUG)
        self.model = model

    def emit(self, record):
        if not self.model.logging_on:
            return
        if record.levelno >= logging.ERROR:
            status, category = Fmi2Status.error, "logStatusError"
        elif record.levelno >= logging.WARNING:
            status, category = Fmi2Status.warning, "logStatusWarning"
        else:
            status, category = Fmi2Status.ok, "logAll"
        message = f"[{record.name}] {record.getMessage()}"
        if record.exc_info:
            message += "\n" + "".join(traceback.format_exception(*record.exc_info))
        self.model.log(message, status, category)


# ================= Loading the user's code =================

def setup_sys_path(interface, resources_dir):
    for path in reversed(interface.get("sys_path", [])):
        path = str((Path(resources_dir) / path).resolve())
        if path not in sys.path:
            sys.path.insert(0, path)


def load_entry(interface, resources_dir):
    setup_sys_path(interface, resources_dir)
    entry = interface["entry"]
    module = importlib.import_module(entry["module"])
    return getattr(module, entry["name"])


def resolve_reference(ref):
    """'package.module:attr.path' -> the object."""
    module_name, _, attr = ref.partition(":")
    return get_path(importlib.import_module(module_name), attr)


def resolve_constant(value):
    if isinstance(value, dict) and len(value) == 1:
        if "python" in value:
            return ast.literal_eval(value["python"])
        if "ref" in value:
            return resolve_reference(value["ref"])
    return value


def get_path(obj, path):
    for part in path.split("."):
        obj = getattr(obj, part)
    return obj


def set_path(obj, path, value):
    *parents, last = path.split(".")
    for part in parents:
        obj = getattr(obj, part)
    setattr(obj, last, value)


def pick(result, key):
    if key is None:
        return result
    if isinstance(result, Mapping):
        return result[key]
    if key.isdigit() and isinstance(result, (tuple, list)):
        return result[int(key)]
    return get_path(result, key)


def describe(source):
    if source["kind"] == "return":
        return "the return value" + (f" [{source['name']!r}]" if source.get("name") else "")
    return f"attribute {source['name']!r}"


def coerce(fmi_type, value):
    if fmi_type == "Real":
        return float(value)
    if fmi_type in ("Integer", "Enumeration"):
        return int(value)
    if fmi_type == "Boolean":
        return bool(value)
    return str(value)


class Fmi2Status:
    """
    Represents the status of an FMI2 FMU or the results of function calls.

    Values:
        * ok: all well
        * warning: an issue has arisen, but the computation can continue.
        * discard: an operation has resulted in invalid output, which must be discarded
        * error: an error has ocurred for this specific FMU instance.
        * fatal: an fatal error has ocurred which has corrupted ALL FMU instances.
        * pending: indicates that the FMu is doing work asynchronously, which can be retrived later.

    Notes:
        FMI section 2.1.3

    """

    ok = 0
    warning = 1
    discard = 2
    error = 3
    fatal = 4
    pending = 5
