"""Generic FMI 3 UniFMU adapter generated by fmugen.

This file is identical for every model. It translates the FMI 3 calls forwarded by
UniFMU's backend (backend.py) into the fmugen runtime engine (fmugen_runtime.py),
which runs the user's unmodified code as described by interface.json.
"""
import sys
from pathlib import Path

try:
    from fmugen_runtime import Status, fraction, make_engine
except ImportError:  # imported from the fmugen package (build probe, tests)
    from fmugen.templates.fmugen_runtime import Status, fraction, make_engine

# Frozen with PyInstaller (fmugen build --compile), data files are in sys._MEIPASS;
# with Nuitka, next to the compiled modules, as in a normal FMU.
RESOURCES_DIR = Path(getattr(sys, "_MEIPASS", None) or Path(__file__).resolve().parent)


class Model:
    def __init__(
            self,
            instance_name,
            instantiation_token,
            resource_path,
            visible,
            logging_on,
            event_mode_used,
            early_return_allowed,
            required_intermediate_variables,
            _log_callback,
            resources_dir=None,
    ) -> None:
        self.instance_name = instance_name
        self.instantiation_token = instantiation_token
        self.event_mode_used = event_mode_used
        self._log_callback = _log_callback # Removing this line will break logging
        self.engine = make_engine(resources_dir or RESOURCES_DIR, self.log, info_category="logEvents")
        # Messages are always forwarded; UniFMU filters them by the importer's logging settings.

    # ================= doStep and updateDiscreteStates =================

    def fmi3DoStep(
            self,
            current_communication_point: float,
            communication_step_size: float,
            no_set_fmu_state_prior_to_current_point: bool,
    ):
        status, event_needed = self.engine.do_step(current_communication_point, communication_step_size)
        if event_needed and not self.event_mode_used:
            self.log("an output clock ticked, but the importer does not use event mode; the tick is dropped",
                     Fmi3Status.warning, "logStatusWarning")
            event_needed = False
            for name, clock in self.engine.clocks.items():
                if clock["causality"] == "output":
                    self.engine.clock_active[name] = False
        early_return = False  # a Python step runs to completion
        return (
            status,
            event_needed,
            self.engine.terminate_requested,
            early_return,
            current_communication_point + communication_step_size,
        )

    def fmi3UpdateDiscreteStates(self):
        status, terminate, next_event_time = self.engine.update_discrete_states()
        return (
            status,
            False,                          # discrete_states_need_update
            terminate,
            False,                          # nominals_continuous_states_changed
            False,                          # values_continuous_states_changed
            next_event_time is not None,    # next_event_time_defined
            next_event_time if next_event_time is not None else 0.0,
        )

    # ================= Initialization, Enter, Termination, and Reset =================

    def fmi3EnterInitializationMode(
            self,
            tolerance_defined: bool,
            tolerance: float,
            start_time: float,
            stop_time_defined: bool,
            stop_time: float
    ):
        self.engine.setup_experiment(
            start_time, stop_time if stop_time_defined else None, tolerance if tolerance_defined else None
        )
        return self.engine.enter_initialization_mode()

    def fmi3ExitInitializationMode(self):
        return self.engine.exit_initialization_mode(next_mode="event" if self.event_mode_used else "step")

    def fmi3EnterEventMode(self):
        return self.engine.enter_event_mode()

    def fmi3EnterStepMode(self):
        return self.engine.enter_step_mode()

    def fmi3EnterConfigurationMode(self):
        return self.engine.enter_configuration_mode()

    def fmi3ExitConfigurationMode(self):
        return self.engine.exit_configuration_mode()

    def fmi3Terminate(self):
        return self.engine.terminate()

    def fmi3Reset(self):
        return self.engine.reset()

    # ================= Serialization =================

    def fmi3SerializeFmuState(self):
        return self.engine.serialize()

    def fmi3DeserializeFmuState(self, bytes: bytes):
        return self.engine.deserialize(bytes)

    # ================= Getters =================

    def fmi3GetFloat32(self, value_references):
        return self.engine.get_values(value_references)

    def fmi3GetFloat64(self, value_references):
        return self.engine.get_values(value_references)

    def fmi3GetInt8(self, value_references):
        return self.engine.get_values(value_references)

    def fmi3GetUInt8(self, value_references):
        return self.engine.get_values(value_references)

    def fmi3GetInt16(self, value_references):
        return self.engine.get_values(value_references)

    def fmi3GetUInt16(self, value_references):
        return self.engine.get_values(value_references)

    def fmi3GetInt32(self, value_references):
        return self.engine.get_values(value_references)

    def fmi3GetUInt32(self, value_references):
        return self.engine.get_values(value_references)

    def fmi3GetInt64(self, value_references):
        return self.engine.get_values(value_references)

    def fmi3GetUInt64(self, value_references):
        return self.engine.get_values(value_references)

    def fmi3GetBoolean(self, value_references):
        return self.engine.get_values(value_references)

    def fmi3GetString(self, value_references):
        return self.engine.get_values(value_references)

    def fmi3GetBinary(self, value_references):
        return self.engine.get_values(value_references)

    def fmi3GetClock(self, value_references):
        return self.engine.get_clocks(value_references)

    def fmi3GetIntervalDecimal(self, value_references):
        return self.engine.get_intervals(value_references)

    def fmi3GetIntervalFraction(self, value_references):
        status, intervals, qualifiers = self.engine.get_intervals(value_references)
        counters, resolutions = zip(*[fraction(i) for i in intervals]) if intervals else ((), ())
        return status, list(counters), list(resolutions), qualifiers

    def fmi3GetShiftDecimal(self, value_references):
        return self.engine.get_shifts(value_references)

    def fmi3GetShiftFraction(self, value_references):
        status, shifts = self.engine.get_shifts(value_references)
        counters, resolutions = zip(*[fraction(s) for s in shifts]) if shifts else ((), ())
        return status, list(counters), list(resolutions)

    # ================= Setters =================

    def fmi3SetFloat32(self, value_references, values):
        return self.engine.set_values(value_references, values)

    def fmi3SetFloat64(self, value_references, values):
        return self.engine.set_values(value_references, values)

    def fmi3SetInt8(self, value_references, values):
        return self.engine.set_values(value_references, values)

    def fmi3SetUInt8(self, value_references, values):
        return self.engine.set_values(value_references, values)

    def fmi3SetInt16(self, value_references, values):
        return self.engine.set_values(value_references, values)

    def fmi3SetUInt16(self, value_references, values):
        return self.engine.set_values(value_references, values)

    def fmi3SetInt32(self, value_references, values):
        return self.engine.set_values(value_references, values)

    def fmi3SetUInt32(self, value_references, values):
        return self.engine.set_values(value_references, values)

    def fmi3SetInt64(self, value_references, values):
        return self.engine.set_values(value_references, values)

    def fmi3SetUInt64(self, value_references, values):
        return self.engine.set_values(value_references, values)

    def fmi3SetBoolean(self, value_references, values):
        return self.engine.set_values(value_references, values)

    def fmi3SetString(self, value_references, values):
        return self.engine.set_values(value_references, values)

    def fmi3SetBinary(self, value_references, value_sizes, values):
        return self.engine.set_values(value_references, values)

    def fmi3SetClock(self, value_references, values):
        return self.engine.set_clocks(value_references, values)

    def fmi3SetIntervalDecimal(self, value_references, intervals):
        return self.engine.set_intervals(value_references, intervals)

    def fmi3SetIntervalFraction(self, value_references, counters, resolutions):
        return self.engine.set_intervals(
            value_references, [float(c) / float(r) for c, r in zip(counters, resolutions)]
        )

    def fmi3SetShiftDecimal(self, value_references, shifts):
        return self.engine.set_shifts(value_references, shifts)

    def fmi3SetShiftFraction(self, value_references, counters, resolutions):
        return self.engine.set_shifts(
            value_references, [float(c) / float(r) for c, r in zip(counters, resolutions)]
        )

    # ================= Logging =================

    def fmi3SetDebugLogging(self, categories, logging_on):
        self.engine.logging_on = bool(logging_on)
        return Fmi3Status.ok

    def log(self, message, status, category = "logEvents"):
        # Removing the line below will break logging.
        self._log_callback(status, category, message)


class Fmi3Status(Status):
    """
    Represents the status of an FMI3 FMU or the results of function calls.

    Values:
        * ok: all well
        * warning: an issue has arisen, but the computation can continue.
        * discard: an operation has resulted in invalid output, which must be discarded
        * error: an error has ocurred for this specific FMU instance.
        * fatal: an fatal error has ocurred which has corrupted ALL FMU instances.

    Notes:
        FMI section 2.2.3
    """
